# Created with WinGet Releaser using komac v2.11.2
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.9.0.schema.json

PackageIdentifier: Nushell.Nushell
PackageVersion: 0.104.1
InstallerLocale: en-US
InstallerType: wix
Scope: user
InstallModes:
- interactive
- silent
- silentWithProgress
UpgradeBehavior: install
Commands:
- nu
ReleaseDate: 2025-05-13
InstallationMetadata:
  DefaultInstallLocation: nu
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/nushell/nightly/releases/download/v0.104.1/nu-0.104.1-x86_64-pc-windows-msvc.msi
  InstallerSha256: 588FB3156059D1363060B77C4D87E9B85DAAF93991AF53985CA611C1B6F1115E
  ProductCode: '{33467914-5777-4000-97AF-DB65F926EE4F}'
  AppsAndFeaturesEntries:
  - DisplayName: Nushell
    ProductCode: '{33467914-5777-4000-97AF-DB65F926EE4F}'
    UpgradeCode: '{82D756D2-19FA-4F09-B10F-64942E89F364}'
- Architecture: arm64
  InstallerUrl: https://github.com/nushell/nightly/releases/download/v0.104.1/nu-0.104.1-aarch64-pc-windows-msvc.msi
  InstallerSha256: A76AE4A9CC11DD0CEF86CF011BBD195E7850444471A50F7F44209869C359A901
  ProductCode: '{33534361-CE47-4056-8A1F-061819E65461}'
  AppsAndFeaturesEntries:
  - DisplayName: Nushell
    ProductCode: '{33534361-CE47-4056-8A1F-061819E65461}'
    UpgradeCode: '{82D756D2-19FA-4F09-B10F-64942E89F364}'
ManifestType: installer
ManifestVersion: 1.9.0
